### ISSUE TITLE
Lab3_eDiscovery_Premium_Task 07_Step 03 Issue (Export option NOT available)

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/SC-5007-Implement-retention-eDiscovery-and-Communication-compliance-in-Microsoft-Purview#15]
# Lab: 03
### Step: 03

In step 3, it states "_Select the drop-down for Actions > Export_", but the **Export** option is not available in the **Actions** drop-down list.

![image](https://github.com/user-attachments/assets/e01c2c1f-b9c0-4f40-83d2-65b0fe944bda)

**Comment by riswinto** [comment]
Hi @Nimra-Maryam! This may have occurred due to the user who's conducting the search not having access to the case. From the screenshot it looks like MOD Administrator is performing the actions of the case investigation, so MOD Administrator would need eDiscovery Manager permissions in Task 1 as well as being added to the case as a user in Task 2. Since eDiscovery allows direct access to user files, additional permissions are needed outside of global administrator to perform certain steps.

I hope that helps!
